// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7CsBCnCSifc4eEXWTI8WWtg2OyH0xxD0',
    appId: '1:504484140168:web:15a1e17d96d725df8d3b3d',
    messagingSenderId: '504484140168',
    projectId: 'sugarmate-3a4a9',
    authDomain: 'sugarmate-3a4a9.firebaseapp.com',
    storageBucket: 'sugarmate-3a4a9.firebasestorage.app',
    measurementId: 'G-SKF9C5P066',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq6YNa78UZ3po8QgPxBIqyUWysruvE-tk',
    appId: '1:504484140168:android:03d4eccef4d92f4c8d3b3d',
    messagingSenderId: '504484140168',
    projectId: 'sugarmate-3a4a9',
    storageBucket: 'sugarmate-3a4a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC57y4mXbUlqXzOGdfDnYtoOJ9vOnbEew0',
    appId: '1:504484140168:ios:c338581ebe31be2e8d3b3d',
    messagingSenderId: '504484140168',
    projectId: 'sugarmate-3a4a9',
    storageBucket: 'sugarmate-3a4a9.firebasestorage.app',
    iosBundleId: 'com.example.sugarMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC57y4mXbUlqXzOGdfDnYtoOJ9vOnbEew0',
    appId: '1:504484140168:ios:c338581ebe31be2e8d3b3d',
    messagingSenderId: '504484140168',
    projectId: 'sugarmate-3a4a9',
    storageBucket: 'sugarmate-3a4a9.firebasestorage.app',
    iosBundleId: 'com.example.sugarMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7CsBCnCSifc4eEXWTI8WWtg2OyH0xxD0',
    appId: '1:504484140168:web:6ed77656e6a30fcf8d3b3d',
    messagingSenderId: '504484140168',
    projectId: 'sugarmate-3a4a9',
    authDomain: 'sugarmate-3a4a9.firebaseapp.com',
    storageBucket: 'sugarmate-3a4a9.firebasestorage.app',
    measurementId: 'G-XP9Q5ZMST2',
  );
}
